name: OpenSTL
channels:
  - pytorch
  - conda-forge
  - nvidia
  - defaults
dependencies:
  - numpy
  - hickle
  - pip
  - python<=3.10.8
  - pytorch<=2.1.1
  - torchvision
  - pytorch-cuda=12.1
  - pytorch-lightning<=1.9.5
  - xarray==0.19.0
  - pip:
    - decord
    - fvcore
    - lpips
    - pandas
    - scikit-image<=0.19.3
    - timm<=0.6.11
    - tqdm
    - dill
    - einops
    - wandb
