N_S: 2
N_T: 6
aft_seq_length: 1
batch_size: 16
ckpt_path: null
clip_grad: null
clip_mode: norm
config_file: configs/kitticaltech/SimVP.py
data_root: ./data
dataname: kitticaltech
decay_epoch: 100
decay_rate: 0.1
deterministic: false
device: cuda
dist: false
drop: 0.0
drop_last: false
drop_path: 0.2
epoch: 200
ex_name: kitti_SimVP
filter_bias_and_bn: false
final_div_factor: 10000.0
fp16: false
fps: false
gpus:
- 0
hid_S: 64
hid_T: 256
in_shape:
- 10
- 3
- 128
- 160
log_step: 1
lr: 0.005
lr_k_decay: 1.0
method: simvp
metric_for_bestckpt: val_loss
metrics:
- mse
- mae
- ssim
- psnr
- lpips
min_lr: 1.0e-06
model_type: gSTA
momentum: 0.9
no_display_method_info: false
num_workers: 4
opt: adam
opt_betas: null
opt_eps: null
overwrite: true
pre_seq_length: 10
res_dir: work_dirs
save_dir: work_dirs/kitti_SimVP
sched: onecycle
seed: 42
spatio_kernel_dec: 3
spatio_kernel_enc: 3
steps_per_epoch: 233
test: false
test_mean: 0
test_std: 1
torchscript: false
total_length: 11
use_augment: false
use_prefetcher: false
val_batch_size: 16
warmup_epoch: 0
warmup_lr: 1.0e-05
weight_decay: 0.0
