aft_seq_length: 10
batch_size: 16
ckpt_path: null
clip_grad: null
clip_mode: norm
config_file: configs/mmnist/SwinLSTM-D.py
data_name: mnist
data_root: ./data
dataname: mmnist
decay_epoch: 100
decay_rate: 0.1
depths_downsample: 2,6
depths_upsample: 6,2
deterministic: false
device: cuda
dist: false
drop: 0.0
drop_last: false
drop_path: 0.0
embed_dim: 128
epoch: 200
ex_name: mmnist_SwinLSTM
filter_bias_and_bn: false
final_div_factor: 10000.0
fp16: false
fps: false
gpus:
- 0
in_shape:
- 10
- 1
- 64
- 64
log_step: 1
lr: 0.0001
lr_k_decay: 1.0
method: swinlstm_d
metric_for_bestckpt: val_loss
metrics:
- mse
- mae
- ssim
- psnr
min_lr: 1.0e-06
model_type: null
momentum: 0.9
no_display_method_info: false
num_heads: 4,8
num_workers: 4
opt: adam
opt_betas: null
opt_eps: null
overwrite: true
patch_size: 2
pre_seq_length: 10
res_dir: work_dirs
save_dir: work_dirs/mmnist_SwinLSTM
sched: onecycle
seed: 42
steps_per_epoch: 625
test: false
test_mean: 0
test_std: 1
torchscript: false
total_length: 20
use_augment: false
use_prefetcher: false
val_batch_size: 16
warmup_epoch: 0
warmup_lr: 1.0e-05
weight_decay: 0.0
window_size: 4
